name: tableau-session-api
channels:
  - defaults
dependencies:
  - python=3.9.12
  - requests=2.28.1
  - flask=2.0.2
  - gunicorn=20.1.0
  - pip=21.2.4
  - pip:
    - python-dotenv==0.19.2
    - pyjwt[crypto]==2.4.0
